default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: kanban_development

test:
  <<: *default
  database: kanban_test

production:
  <<: *default
  database: kanban_production
  username: kanban_production
  password: <%= ENV['KANBAN_DATABASE_PASSWORD'] %>
